### PR TITLE
Hawk driver

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
Hawk driver disassembled and understood

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello! In order to ease the navigation i've re-enabled "label-relative", but tweaked conditions. Now it will be used if there is a user-specified label in the beginning of instruction. No "L_xxxx" will be auto-generated. If there is an "R_xxxx" label generated from a reloc, you'll see it as you wanted.

And accesses inside pstrings now use the same mechanism, you'll see "StringLabel+offset"

**Comment by phire** [comment]
There are still examples of it going wrong, for example:

```diff
Reloc is abandoned in favour of auto-label
-- c7a9:    d6 ab c8 13          st S, [R_c813|0xc813]
++ c7a9:    d6 ab c8 13          st S, [L_c811+2|0xc813]

and Reloc is abandoned in favour of different reloc
-- c7af:    a1 c8 5c             st AL, [R_c85c|0xc85c]
++ c7af:    a1 c8 5c             st AL, [R_c85b+1|0xc85c]
```

I'm going to merge anyway, and fix later

**Comment by phire** [comment]
Think I'm going to need to implement label priority to get it working how you want. 

Personally, I just want to make it explictly show labels in the middle of instructions (and then auto-label them)

**Comment by Sonic-Amiga** [comment]
No no, as i have said, in fact any approach is fine, i just want to be able to see instructions, inside of which referenced addresses are located.

**Pull request merged**
